<?php
/**
 * The contents of this file was generated using the WSDLs as provided by eBay.
 *
 * DO NOT EDIT THIS FILE!
 */

namespace DTS\eBaySDK\RestAPI\Enums;

/**
 *
 */
class EnumTokenType
{
    const C_FIVE = 'Five';
    const C_FOUR = 'Four';
    const C_SIX = 'Six';
}
