<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\MerchantAPI\Enums;

class EnumStringType
{
    const C_VALUE_ONE = 'ValueOne';
    const C_VALUE_THREE = 'Value  Three';
    const C_VALUE_TWO = 'Value Two';
}
