<?php
/**
 * DO NOT EDIT THIS FILE BEYOND THIS COMMENT!
 *
 * THE CODE IN THIS FILE WAS GENERATED FROM THE EBAY WSDL USING THE PROJECT:
 *
 * https://github.com/davidtsadler/ebay-api-sdk-php
 */

namespace DTS\eBaySDK\MerchantAPI\Services;

class MerchantAPIService extends \DTS\eBaySDK\MerchantAPI\Services\MerchantAPIBaseService
{
    const API_VERSION = '1.2.3';

    /**
     * @param array $config Configuration option values.
     */
    public function __construct(array $config)
    {
        parent::__construct($config);
    }

    /**
     * @param \DTS\eBaySDK\MerchantAPI\Types\MethodOneRequestType $request
     * @return \DTS\eBaySDK\MerchantAPI\Types\ComplexType
     */
    public function methodOne(\DTS\eBaySDK\MerchantAPI\Types\MethodOneRequestType $request)
    {
        return $this->callOperation(
            'MethodOne',
            $request,
            '\DTS\eBaySDK\MerchantAPI\Types\ComplexType'
        );
    }

    /**
     * @param \DTS\eBaySDK\MerchantAPI\Types\MethodTwoRequestType $request
     * @return \DTS\eBaySDK\MerchantAPI\Types\ComplexType
     */
    public function methodTwo(\DTS\eBaySDK\MerchantAPI\Types\MethodTwoRequestType $request)
    {
        return $this->callOperation(
            'methodTwo',
            $request,
            '\DTS\eBaySDK\MerchantAPI\Types\ComplexType'
        );
    }
}

