<?php
/**
 * The contents of this file was generated using the WSDLs as provided by eBay.
 *
 * DO NOT EDIT THIS FILE!
 */

namespace DTS\eBaySDK\FindingAPI\Enums;

/**
 *
 */
class EnumStringType
{
    const C_VALUE_ONE = 'ValueOne';
    const C_VALUE_THREE = 'Value  Three';
    const C_VALUE_TWO = 'Value Two';
}
