<?php
/**
 * DO NOT EDIT THIS FILE BEYOND THIS COMMENT!
 *
 * THE CODE IN THIS FILE WAS GENERATED FROM THE EBAY WSDL USING THE PROJECT:
 *
 * https://github.com/davidtsadler/ebay-api-sdk-php
 */

namespace DTS\eBaySDK\FindingAPI\Enums;

/**
 *
 */
class EnumStringType
{
    const C_VALUE_ONE = 'ValueOne';
    const C_VALUE_THREE = 'Value  Three';
    const C_VALUE_TWO = 'Value Two';
}
