<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\FindingAPI\Enums;

class EnumTokenType
{
    const C_FIVE = 'Five';
    const C_FOUR = 'Four';
    const C_SIX = 'Six';
}
