<?php
/**
 * DO NOT EDIT THIS FILE BEYOND THIS COMMENT!
 *
 * THE CODE IN THIS FILE WAS GENERATED FROM THE EBAY WSDL USING THE PROJECT:
 *
 * https://github.com/davidtsadler/ebay-api-sdk-php
 */

namespace DTS\eBaySDK\FindingAPI\Enums;

/**
 *
 */
class EnumTokenType
{
    const C_FIVE = 'Five';
    const C_FOUR = 'Four';
    const C_SIX = 'Six';
}
